import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import fs from 'fs/promises';
import path from 'path';

async function createForm() {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4 size
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  page.drawText('Scheme Application Form', { x: 50, y: 800, size: 24, font });
  page.drawText('This form is auto-generated by SchemeSaathi', { x: 50, y: 780, size: 10, font, color: rgb(0.5, 0.5, 0.5) });

  const form = pdfDoc.getForm();

  // Name field
  page.drawText('Applicant Name:', { x: 50, y: 730, size: 12, font });
  const nameField = form.createTextField('applicant_name');
  nameField.addToPage(page, { x: 150, y: 725, width: 300, height: 20 });

  // Age field
  page.drawText('Age:', { x: 50, y: 690, size: 12, font });
  const ageField = form.createTextField('applicant_age');
  ageField.addToPage(page, { x: 150, y: 685, width: 100, height: 20 });

  // Gender field
  page.drawText('Gender:', { x: 50, y: 650, size: 12, font });
  const genderField = form.createTextField('applicant_gender');
  genderField.addToPage(page, { x: 150, y: 645, width: 150, height: 20 });

  // State field
  page.drawText('State:', { x: 50, y: 610, size: 12, font });
  const stateField = form.createTextField('applicant_state');
  stateField.addToPage(page, { x: 150, y: 605, width: 200, height: 20 });

  // Occupation field
  page.drawText('Occupation:', { x: 50, y: 570, size: 12, font });
  const occupationField = form.createTextField('applicant_occupation');
  occupationField.addToPage(page, { x: 150, y: 565, width: 200, height: 20 });
  
  // Income field
  page.drawText('Annual Income:', { x: 50, y: 530, size: 12, font });
  const incomeField = form.createTextField('applicant_income');
  incomeField.addToPage(page, { x: 150, y: 525, width: 200, height: 20 });

  // Scheme applied for
  page.drawText('Scheme ID:', { x: 50, y: 490, size: 12, font });
  const schemeField = form.createTextField('scheme_id');
  schemeField.addToPage(page, { x: 150, y: 485, width: 300, height: 20 });

  const templatesDir = path.join(process.cwd(), 'data', 'templates');
  await fs.mkdir(templatesDir, { recursive: true });
  
  const pdfBytes = await pdfDoc.save();
  await fs.writeFile(path.join(templatesDir, 'base_form.pdf'), pdfBytes);
  
  console.log('Created base_form.pdf successfully.');
}

createForm().catch(console.error);
